lista = ['AGRACINALDO','ANOTARAPIDIZ', 'BARRIGUDINHO','BELINHA','BRUTOAOSMONTES', 'DEEPWEB','DOCTORZILDA','HOMEOPATO','LIRIRICA','LUCKYSWALTERSEN','MASTERTOPSUPERDIRETORGERENTECHEFE', 'PAPAIGOVEL','ROUCOBOLE', 'SEMSALARIUS','SUCUBINHA', 'VEDELONGE', 'XUXULEH','YOLEIRRI']
for i in lista:
  print(i)
